version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - 'app'
    ports:
      - 8080:80
  db:
    image: postgres
    ports:
      - '5432:5432'
  redis:
    image: 'redis:4.0.8-alpine'
    command: redis-server --requirepass yourpassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/mapAPI
    env_file:
      - '.env'
    depends_on:
      - 'db'
      - 'redis'
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/mapAPI'
    env_file:
      - '.env'
volumes:
  redis:
  postgres:
